name: facecode
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  like_button: ^2.0.5
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.14.0
  firebase_core:
  agora_uikit: ^1.3.8
  firebase_auth: ^4.17.8
  provider: ^6.1.2
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  cached_network_image: ^3.3.1
  csc_picker: ^0.2.7
  insta_image_viewer: ^1.0.4
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.jpg"
  adaptive_icon_foreground: "images/icon_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
