// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSUUqrcPKjGEBe0KLKcx2hi-lS-3LJUC4',
    appId: '1:170416815396:web:b0c0ec5a4293c8811247b1',
    messagingSenderId: '170416815396',
    projectId: 'facecode-chat',
    authDomain: 'facecode-chat.firebaseapp.com',
    storageBucket: 'facecode-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUDaqPqercu7jlchFNAD7ZR-viANkZxA',
    appId: '1:170416815396:android:9eab7b89915615991247b1',
    messagingSenderId: '170416815396',
    projectId: 'facecode-chat',
    storageBucket: 'facecode-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ-nl1esrDrlENbqYLh1Ece97blpU-_Ss',
    appId: '1:170416815396:ios:5c814fe81a43e90d1247b1',
    messagingSenderId: '170416815396',
    projectId: 'facecode-chat',
    storageBucket: 'facecode-chat.appspot.com',
    iosBundleId: 'com.example.facecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ-nl1esrDrlENbqYLh1Ece97blpU-_Ss',
    appId: '1:170416815396:ios:3e1f899300a51c8b1247b1',
    messagingSenderId: '170416815396',
    projectId: 'facecode-chat',
    storageBucket: 'facecode-chat.appspot.com',
    iosBundleId: 'com.example.facecode.RunnerTests',
  );
}
